# Generated by Django 3.2.8 on 2021-10-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211030_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.CharField(blank=True, max_length=100, verbose_name='Количество'),
        ),
    ]
